version: '3.8'

services:
  mariadb:
    image: mariadb:lts
    container_name: neticrm-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./container/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - neticrm_network

  php-fpm:
    image: neticrm:php-only-d10
    container_name: neticrm-php
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./container/init-10.sh:/init.sh
      - /mnt/neticrm-10:/mnt/neticrm-10
      - ./container/supervisord/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - mariadb
    networks:
      - neticrm_network

  nginx:
    image: nginx:stable
    container_name: neticrm-nginx
    restart: always
    ports:
      - "${PORT}:80"
    volumes:
      - ./www:/var/www/html
      - /mnt/neticrm-10:/mnt/neticrm-10
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - neticrm_network

networks:
  neticrm_network:
    driver: bridge